application: pro-jeffreiher
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "60d"

handlers:
# order matters 
- url: /*.svg
  static_files: jreiher/static/images/images_dest/*.svg
  upload: jreiher/static/images/images_dest/*.svg
  mime_type: image/svg+xml

- url: /static
  static_dir: jreiher/static 

- url: .*
  script: jreiher.app

skip_files:
- ^(node_modules)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$


libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"